version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-anon
    restart: always
    ports:
      - 27023:27017
    volumes:
      - db-data:/data/db
  anon-message:
    image: anon-message
    container_name: anon-message
    restart: always
    depends_on:
      - mongodb
    ports:
      - 3009:3000
volumes:
  db-data:
    driver: local